### ISSUE TITLE
Robokassa Gateway

### ISSUE THREAD

**Issue by SHELA** [hiqdev/omnipay-robokassa#1]
Hi. Tried and what get:
: Uncaught exception 'Omnipay\Common\Exception\RuntimeException' with message 'Class '\Omnipay\robokassa\Gateway' not found' in

**Comment by hiqsol** [comment]
Hi.
Sorry, busy today. 
I'll look into it tomorrow and give you answer.

**Comment by hiqsol** [comment]
Unfortunately, this package is just a stub for the moment.
We'll definitely proceed with it but a bit later.

**Comment by hiqsol** [comment]
The issue not valid at the moment.
The package was fixed to work.
