### ISSUE TITLE
Параметр Receipt

### ISSUE THREAD

**Issue by andchir** [hiqdev/omnipay-robokassa#4]
Спасибо Вам за обновление компонента для omnipay3!
Планируется ли добавить поддержку параметра Receipt?
https://docs.robokassa.ru/?_ga=2.13294135.1475586134.1556356016-236381731.1555837198#6872

**Comment by SilverFire** [comment]
Здравствуйте.
Мы этим параметром не пользуемся, но с удовольствием примем от вас Pull Request, добавляющий поддержку Recepit.

**Comment by andchir** [comment]
Сделал Pull Request, но там ещё есть изменения по валюте.
