### ISSUE TITLE
Нотификация Success Url и Fail Url

### ISSUE THREAD

**Issue by ermilov** [hiqdev/omnipay-robokassa#6]
Подскажите пожалуйста, как реализовать прием уведомлений через omnipay

В реквесте у меня приходят все необходимые для подтверждения данные, но как их обработать через omnipay я не могу понять

**Comment by SilverFire** [comment]
Здравствуйте!

Ваш вопрос слишком общий но попробую ответить :) Если у вас есть endpoint `example.com/merchant/robokassa/success.php`, то вам нужно что-то типа такого:

```php
use Omnipay\Omnipay;

require_once __DIR__ . '/../../../autoload.php';

$gateway = Omnipay::create('RoboKassa');
$gateway->setPurse('abc123');
$gateway->setSecretKey('qwerty');
$gateway->setSecretKey2('ytrewq');

$response = $gateway->completePurchase($_POST)->send();

if ($response->isSuccessful()) {
    // payment was successful: update database
    print_r($response);
} else {
    // payment failed: display message to customer
    die();
}
```

**Comment by ermilov** [comment]
Это именно то, что мне необходимо. Спасибо!
